// components/NutrientDisplay.jsx - Detailed Nutrient & Macro Visualizer
import React from 'react';
import {
  Flame,
  Activity,
  Heart,
  CheckCircle,
  Lightbulb,
  Info,
  Sparkles,
  PieChart,
  ChefHat,
} from 'lucide-react';

export default function NutrientDisplay({ data, aiNotice, usedAi }) {
  if (!data) return null;

  const {
    foodName,
    servingSize,
    calories,
    macros = {},
    vitaminsAndMinerals = [],
    ingredients = [],
    dietaryTags = [],
    healthScore = 85,
    healthSummary,
    recommendation,
  } = data;

  const protein = macros.protein || 0;
  const carbs = macros.carbs || 0;
  const fats = macros.fats || 0;
  const fiber = macros.fiber || 0;
  const sugar = macros.sugar || 0;

  // Calculate macro calorie contributions for visual progress bar
  const proteinCal = protein * 4;
  const carbsCal = carbs * 4;
  const fatsCal = fats * 9;
  const totalMacroCal = proteinCal + carbsCal + fatsCal || 1;

  const proteinPct = Math.round((proteinCal / totalMacroCal) * 100);
  const carbsPct = Math.round((carbsCal / totalMacroCal) * 100);
  const fatsPct = Math.round((fatsCal / totalMacroCal) * 100);

  return (
    <div className="glass-card glass-card-glow" style={{ padding: '2rem' }}>
      {/* AI Mode Banner */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '0.75rem',
          padding: '0.75rem 1rem',
          borderRadius: '12px',
          background: usedAi ? 'rgba(16, 185, 129, 0.1)' : 'rgba(245, 158, 11, 0.1)',
          border: `1px solid ${usedAi ? 'rgba(16, 185, 129, 0.3)' : 'rgba(245, 158, 11, 0.3)'}`,
          marginBottom: '1.5rem',
        }}
      >
        <Sparkles size={20} color={usedAi ? '#34d399' : '#fbbf24'} />
        <div style={{ fontSize: '0.85rem', color: usedAi ? '#a7f3d0' : '#fde68a' }}>
          {aiNotice || 'Nutritional breakdown generated by Gemini Vision AI.'}
        </div>
      </div>

      {/* Header: Food Title, Serving Size & Health Score */}
      <div
        style={{
          display: 'flex',
          flexWrap: 'wrap',
          alignItems: 'flex-start',
          justifyContent: 'space-between',
          gap: '1rem',
          paddingBottom: '1.5rem',
          borderBottom: '1px solid var(--border-subtle)',
          marginBottom: '1.5rem',
        }}
      >
        <div>
          <h2 style={{ fontSize: '1.85rem', marginBottom: '0.25rem', color: '#ffffff' }}>
            {foodName}
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.92rem' }}>
            Portion: <strong style={{ color: '#ffffff' }}>{servingSize || '1 serving'}</strong>
          </p>
        </div>

        {/* Health Score Pill */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '0.85rem',
            background: 'rgba(16, 185, 129, 0.12)',
            padding: '0.6rem 1.2rem',
            borderRadius: '16px',
            border: '1px solid rgba(16, 185, 129, 0.35)',
          }}
        >
          <div
            style={{
              width: '42px',
              height: '42px',
              borderRadius: '50%',
              background: 'linear-gradient(135deg, #10b981, #059669)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 800,
              fontSize: '1.1rem',
              color: '#ffffff',
            }}
          >
            {healthScore}
          </div>
          <div>
            <div style={{ fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: '#34d399', fontWeight: 700 }}>
              Health Score
            </div>
            <div style={{ fontSize: '0.88rem', fontWeight: 600, color: '#ffffff' }}>
              {healthScore >= 80 ? 'Excellent Choice' : healthScore >= 60 ? 'Moderate Balance' : 'Indulgent Meal'}
            </div>
          </div>
        </div>
      </div>

      {/* Dietary Tags */}
      {dietaryTags && dietaryTags.length > 0 && (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '1.75rem' }}>
          {dietaryTags.map((tag, i) => (
            <span
              key={i}
              style={{
                fontSize: '0.8rem',
                fontWeight: 600,
                padding: '0.3rem 0.8rem',
                borderRadius: '999px',
                background: 'rgba(255, 255, 255, 0.05)',
                border: '1px solid var(--border-subtle)',
                color: '#e2e8f0',
              }}
            >
              ✓ {tag}
            </span>
          ))}
        </div>
      )}

      {/* Calories & Macro Cards */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
          gap: '1rem',
          marginBottom: '1.75rem',
        }}
      >
        {/* Calories */}
        <div
          style={{
            background: 'rgba(249, 115, 22, 0.08)',
            border: '1px solid rgba(249, 115, 22, 0.25)',
            borderRadius: '16px',
            padding: '1.25rem',
            textAlign: 'center',
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '0.35rem' }}>
            <Flame size={24} color="#f97316" />
          </div>
          <div style={{ fontSize: '1.85rem', fontWeight: 800, color: '#ffffff', lineHeight: 1.1 }}>
            {calories}
          </div>
          <div style={{ fontSize: '0.8rem', color: '#fed7aa', marginTop: '0.2rem', fontWeight: 600 }}>
            Calories (kcal)
          </div>
        </div>

        {/* Protein */}
        <div
          style={{
            background: 'rgba(244, 63, 94, 0.08)',
            border: '1px solid rgba(244, 63, 94, 0.25)',
            borderRadius: '16px',
            padding: '1.25rem',
            textAlign: 'center',
          }}
        >
          <div style={{ fontSize: '0.78rem', color: '#fb7185', fontWeight: 700, textTransform: 'uppercase', marginBottom: '0.25rem' }}>
            Protein
          </div>
          <div style={{ fontSize: '1.75rem', fontWeight: 800, color: '#ffffff', lineHeight: 1.1 }}>
            {protein}<span style={{ fontSize: '1rem', fontWeight: 500 }}>g</span>
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.2rem' }}>
            {proteinPct}% of energy
          </div>
        </div>

        {/* Carbs */}
        <div
          style={{
            background: 'rgba(245, 158, 11, 0.08)',
            border: '1px solid rgba(245, 158, 11, 0.25)',
            borderRadius: '16px',
            padding: '1.25rem',
            textAlign: 'center',
          }}
        >
          <div style={{ fontSize: '0.78rem', color: '#fbbf24', fontWeight: 700, textTransform: 'uppercase', marginBottom: '0.25rem' }}>
            Carbs
          </div>
          <div style={{ fontSize: '1.75rem', fontWeight: 800, color: '#ffffff', lineHeight: 1.1 }}>
            {carbs}<span style={{ fontSize: '1rem', fontWeight: 500 }}>g</span>
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.2rem' }}>
            {carbsPct}% of energy
          </div>
        </div>

        {/* Fats */}
        <div
          style={{
            background: 'rgba(99, 102, 241, 0.08)',
            border: '1px solid rgba(99, 102, 241, 0.25)',
            borderRadius: '16px',
            padding: '1.25rem',
            textAlign: 'center',
          }}
        >
          <div style={{ fontSize: '0.78rem', color: '#818cf8', fontWeight: 700, textTransform: 'uppercase', marginBottom: '0.25rem' }}>
            Fats
          </div>
          <div style={{ fontSize: '1.75rem', fontWeight: 800, color: '#ffffff', lineHeight: 1.1 }}>
            {fats}<span style={{ fontSize: '1rem', fontWeight: 500 }}>g</span>
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.2rem' }}>
            {fatsPct}% of energy
          </div>
        </div>

        {/* Fiber */}
        <div
          style={{
            background: 'rgba(16, 185, 129, 0.08)',
            border: '1px solid rgba(16, 185, 129, 0.25)',
            borderRadius: '16px',
            padding: '1.25rem',
            textAlign: 'center',
          }}
        >
          <div style={{ fontSize: '0.78rem', color: '#34d399', fontWeight: 700, textTransform: 'uppercase', marginBottom: '0.25rem' }}>
            Fiber
          </div>
          <div style={{ fontSize: '1.75rem', fontWeight: 800, color: '#ffffff', lineHeight: 1.1 }}>
            {fiber}<span style={{ fontSize: '1rem', fontWeight: 500 }}>g</span>
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.2rem' }}>
            Gut Health
          </div>
        </div>
      </div>

      {/* Multi-segment Macronutrient Proportion Bar */}
      <div style={{ marginBottom: '2rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
          <span>Macronutrient Ratio</span>
          <span>{proteinPct}% Protein • {carbsPct}% Carbs • {fatsPct}% Fat</span>
        </div>
        <div
          style={{
            display: 'flex',
            height: '10px',
            borderRadius: '999px',
            overflow: 'hidden',
            background: 'rgba(255,255,255,0.08)',
          }}
        >
          <div style={{ width: `${proteinPct}%`, background: '#fb7185' }} title={`Protein: ${proteinPct}%`} />
          <div style={{ width: `${carbsPct}%`, background: '#fbbf24' }} title={`Carbs: ${carbsPct}%`} />
          <div style={{ width: `${fatsPct}%`, background: '#818cf8' }} title={`Fat: ${fatsPct}%`} />
        </div>
      </div>

      {/* Ingredients Identified in Image */}
      {ingredients && ingredients.length > 0 && (
        <div style={{ marginBottom: '2rem' }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginBottom: '0.85rem',
            }}
          >
            <h3
              style={{
                fontSize: '1.15rem',
                margin: 0,
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem',
                color: '#ffffff',
              }}
            >
              <ChefHat size={20} color="#f59e0b" />
              <span>Ingredients Used ({ingredients.length})</span>
            </h3>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
              Identified from uploaded meal image
            </span>
          </div>

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: '0.75rem',
            }}
          >
            {ingredients.map((ing, idx) => {
              const name = typeof ing === 'string' ? ing : ing.name;
              const amount = typeof ing === 'object' && ing.amount ? ing.amount : null;
              return (
                <div
                  key={idx}
                  style={{
                    background: 'rgba(245, 158, 11, 0.05)',
                    border: '1px solid rgba(245, 158, 11, 0.2)',
                    borderRadius: '12px',
                    padding: '0.75rem 1rem',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: '0.5rem',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
                    <div
                      style={{
                        width: '8px',
                        height: '8px',
                        borderRadius: '50%',
                        background: '#f59e0b',
                        boxShadow: '0 0 8px rgba(245, 158, 11, 0.6)',
                        flexShrink: 0,
                      }}
                    />
                    <span style={{ fontSize: '0.88rem', fontWeight: 600, color: '#ffffff' }}>
                      {name}
                    </span>
                  </div>
                  {amount && (
                    <span
                      style={{
                        fontSize: '0.75rem',
                        fontWeight: 600,
                        color: '#fbbf24',
                        background: 'rgba(245, 158, 11, 0.15)',
                        padding: '0.2rem 0.5rem',
                        borderRadius: '6px',
                        whiteSpace: 'nowrap',
                      }}
                    >
                      {amount}
                    </span>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Micronutrients List */}
      {vitaminsAndMinerals && vitaminsAndMinerals.length > 0 && (
        <div style={{ marginBottom: '2rem' }}>
          <h3 style={{ fontSize: '1.1rem', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Activity size={18} color="#10b981" /> Essential Vitamins & Minerals
          </h3>
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
              gap: '0.75rem',
            }}
          >
            {vitaminsAndMinerals.map((item, idx) => (
              <div
                key={idx}
                style={{
                  background: 'rgba(255, 255, 255, 0.03)',
                  border: '1px solid var(--border-subtle)',
                  borderRadius: '12px',
                  padding: '0.75rem 1rem',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <span style={{ fontSize: '0.85rem', color: '#e2e8f0', fontWeight: 500 }}>
                  {item.name}
                </span>
                <span style={{ fontSize: '0.85rem', fontWeight: 700, color: '#34d399' }}>
                  {item.amount}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Nutritional Summary & Recommendation */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
          gap: '1rem',
        }}
      >
        {healthSummary && (
          <div
            style={{
              background: 'rgba(255, 255, 255, 0.02)',
              border: '1px solid var(--border-subtle)',
              borderRadius: '14px',
              padding: '1.25rem',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: '#38bdf8' }}>
              <Info size={18} />
              <h4 style={{ fontSize: '0.95rem', margin: 0, color: '#ffffff' }}>Nutrition Insights</h4>
            </div>
            <p style={{ fontSize: '0.88rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>
              {healthSummary}
            </p>
          </div>
        )}

        {recommendation && (
          <div
            style={{
              background: 'rgba(16, 185, 129, 0.05)',
              border: '1px solid rgba(16, 185, 129, 0.25)',
              borderRadius: '14px',
              padding: '1.25rem',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: '#34d399' }}>
              <Lightbulb size={18} />
              <h4 style={{ fontSize: '0.95rem', margin: 0, color: '#ffffff' }}>Dietary Advice</h4>
            </div>
            <p style={{ fontSize: '0.88rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>
              {recommendation}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
