
// components/NutrientDisplay.jsx - Detailed Nutrient & Macro Visualizer

import React from 'react';
import {
  Flame,
  Activity,
  Lightbulb,
  Info,
  Sparkles,
  ChefHat,
  
} from 'lucide-react';

import './NutrientDisplay.css';

export default function NutrientDisplay({ data, aiNotice, usedAi }) {
  if (!data) return null;

  const {
    foodName,
    servingSize,
    calories,
    macros = {},
    vitaminsAndMinerals = [],
    ingredients = [],
    dietaryTags = [],
    healthScore = 85,
    healthSummary,
    recommendation,
  } = data;

  const protein = macros.protein || 0;
  const carbs = macros.carbs || 0;
  const fats = macros.fats || 0;
  const fiber = macros.fiber || 0;

  // Calculate macro calorie contributions
  const proteinCal = protein * 4;
  const carbsCal = carbs * 4;
  const fatsCal = fats * 9;

  const totalMacroCal =
    proteinCal + carbsCal + fatsCal || 1;

  const proteinPct = Math.round(
    (proteinCal / totalMacroCal) * 100
  );

  const carbsPct = Math.round(
    (carbsCal / totalMacroCal) * 100
  );

  const fatsPct = Math.round(
    (fatsCal / totalMacroCal) * 100
  );

  return (
    <div className="nutrient-display glass-card glass-card-glow">

      {/* AI Mode Banner */}
      <div className={`ai-mode-banner ${usedAi ? 'ai-active' : 'ai-fallback'}`}>
        <Sparkles
          size={20}
          className="ai-mode-icon"
        />

        <div className="ai-mode-text">
          {aiNotice ||
            'Nutritional breakdown generated by Gemini Vision AI.'}
        </div>
      </div>

      {/* Header */}
      <div className="nutrient-header">

        <div className="food-heading">
          <h2>{foodName}</h2>

          <p>
            Portion:{' '}
            <strong>
              {servingSize || '1 serving'}
            </strong>
          </p>
        </div>

        {/* Health Score */}
        <div className="health-score-pill">

          <div className="health-score-circle">
            {healthScore}
          </div>

          <div className="health-score-info">
            <div className="health-score-label">
              Health Score
            </div>

            <div className="health-score-text">
              {healthScore >= 80
                ? 'Excellent Choice'
                : healthScore >= 60
                  ? 'Moderate Balance'
                  : 'Indulgent Meal'}
            </div>
          </div>

        </div>
      </div>

      {/* Dietary Tags */}
      {dietaryTags && dietaryTags.length > 0 && (
        <div className="dietary-tags">
          {dietaryTags.map((tag, i) => (
            <span
              key={i}
              className="dietary-tag"
            >
              ✓ {tag}
            </span>
          ))}
        </div>
      )}

      {/* Calories & Macro Cards */}
      <div className="macro-cards">

        {/* Calories */}
        <div className="macro-card calories-card">

          <div className="macro-icon">
            <Flame size={24} />
          </div>

          <div className="macro-value">
            {calories}
          </div>

          <div className="macro-label">
            Calories (kcal)
          </div>
        </div>

        {/* Protein */}
        <div className="macro-card protein-card">

          <div className="macro-title">
            Protein
          </div>

          <div className="macro-value">
            {protein}
            <span className="macro-unit">g</span>
          </div>

          <div className="macro-subtext">
            {proteinPct}% of energy
          </div>
        </div>

        {/* Carbs */}
        <div className="macro-card carbs-card">

          <div className="macro-title">
            Carbs
          </div>

          <div className="macro-value">
            {carbs}
            <span className="macro-unit">g</span>
          </div>

          <div className="macro-subtext">
            {carbsPct}% of energy
          </div>
        </div>

        {/* Fats */}
        <div className="macro-card fats-card">

          <div className="macro-title">
            Fats
          </div>

          <div className="macro-value">
            {fats}
            <span className="macro-unit">g</span>
          </div>

          <div className="macro-subtext">
            {fatsPct}% of energy
          </div>
        </div>

        {/* Fiber */}
        <div className="macro-card fiber-card">

          <div className="macro-title">
            Fiber
          </div>

          <div className="macro-value">
            {fiber}
            <span className="macro-unit">g</span>
          </div>

          <div className="macro-subtext">
            Gut Health
          </div>
        </div>

      </div>

      {/* Macronutrient Ratio */}
      <div className="macro-ratio">

        <div className="macro-ratio-header">
          <span>Macronutrient Ratio</span>

          <span>
            {proteinPct}% Protein • {carbsPct}% Carbs • {fatsPct}% Fat
          </span>
        </div>

        <div className="macro-ratio-bar">

          <div
            className="macro-ratio-protein"
            style={{ width: `${proteinPct}%` }}
            title={`Protein: ${proteinPct}%`}
          />

          <div
            className="macro-ratio-carbs"
            style={{ width: `${carbsPct}%` }}
            title={`Carbs: ${carbsPct}%`}
          />

          <div
            className="macro-ratio-fats"
            style={{ width: `${fatsPct}%` }}
            title={`Fat: ${fatsPct}%`}
          />

        </div>
      </div>

      {/* Ingredients */}
      {ingredients && ingredients.length > 0 && (
        <div className="ingredients-section">

          <div className="section-header">

            <h3>
              <ChefHat
                size={20}
                className="ingredients-icon"
              />

              <span>
                Ingredients Used ({ingredients.length})
              </span>
            </h3>

            <span className="section-description">
              Identified from uploaded meal image
            </span>

          </div>

          <div className="ingredients-grid">

            {ingredients.map((ing, idx) => {

              const name =
                typeof ing === 'string'
                  ? ing
                  : ing.name;

              const amount =
                typeof ing === 'object' &&
                ing.amount
                  ? ing.amount
                  : null;

              return (
                <div
                  key={idx}
                  className="ingredient-item"
                >

                  <div className="ingredient-name">

                    <div className="ingredient-dot" />

                    <span>
                      {name}
                    </span>

                  </div>

                  {amount && (
                    <span className="ingredient-amount">
                      {amount}
                    </span>
                  )}

                </div>
              );
            })}

          </div>
        </div>
      )}

      {/* Vitamins & Minerals */}
      {vitaminsAndMinerals &&
        vitaminsAndMinerals.length > 0 && (
          <div className="vitamins-section">

            <h3 className="section-title">
              <Activity
                size={18}
                className="vitamins-icon"
              />

              Essential Vitamins & Minerals
            </h3>

            <div className="vitamins-grid">

              {vitaminsAndMinerals.map(
                (item, idx) => (
                  <div
                    key={idx}
                    className="vitamin-item"
                  >

                    <span className="vitamin-name">
                      {item.name}
                    </span>

                    <span className="vitamin-amount">
                      {item.amount}
                    </span>

                  </div>
                )
              )}

            </div>
          </div>
        )}

      {/* Summary & Recommendation */}
      <div className="insights-grid">

        {healthSummary && (
          <div className="insight-card nutrition-insight">

            <div className="insight-heading">

              <Info size={18} />

              <h4>
                Nutrition Insights
              </h4>

            </div>

            <p>
              {healthSummary}
            </p>

          </div>
        )}

        {recommendation && (
          <div className="insight-card recommendation-insight">

            <div className="insight-heading">

              <Lightbulb size={18} />

              <h4>
                Dietary Advice
              </h4>

            </div>

            <p>
              {recommendation}
            </p>

          </div>
        )}

      </div>

    </div>
  );
}

